#!/bin/bash

# Tool to make multiple duplicates of a distro sks installation.
# The copies will share a dump, reducing the disk requirements iff the
# original was initialised using 'fastbuild'. 
#
# We assume systemd.

: "${SKS_BASE_DIR=/etc/sks}"
: "${SKS_DATA_DIR=/var/lib/sks}"
: "${SYSTEMD_UNIT_DIR=/lib/systemd/system}"
: "${SYSTEMD_CONF_DIR=/etc/systemd/system}"
: "${SKS_DAEMON_USER=debian-sks}"
: "${SKS_EXTRA_COPIES=2}"

# use cicada method of minimising sync clashes
CICADA_INTERVALS=(17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79)

# shut down main service
systemctl stop sks

# reconfigure main service
perl -pi.bak -e "
  next if /^nodename/;
  next if /^hkp_address/;
  next if /^hkp_port/;
  next if /^recon_address/;
  next if /^recon_port/;
  next if /^gossip_interval/;
  next if /^stat_hour/;
  next if /^use_port_80/;
" "$SKS_BASE_DIR/sksconf"
cat <<EOF >> "$SKS_BASE_DIR/sksconf"

# Added by script
nodename: sks-0
recon_address: 0.0.0.0
recon_port: 11370
hkp_address: 127.0.0.1
hkp_port: 11371
gossip_interval: ${CICADA_INTERVALS[0]}
stat_hour: 0
EOF

# add main node to (shared) membership
echo "127.0.0.1 11370 # sks-0" >> "$SKS_BASE_DIR/membership"

for i in $(seq 1 $SKS_EXTRA_COPIES); do
  basedir="${SKS_BASE_DIR}-$i"
  datadir="${SKS_DATA_DIR}-$i"
  nodename="sks-$i"
  recon_port=$(( 20370 + i * 1000 ))
  hkp_port=$(( 20371 + i * 1000 ))
  daemon_user="${SKS_DAEMON_USER}-$i"

  # clone datadir but share dump read-only
  rsync -a --exclude dump "$SKS_DATA_DIR" "$datadir"
  chown -R "$daemon_user:$daemon_user" "$datadir"
  ln -s "${SKS_DATA_DIR}/dump" "$datadir/"

  mkdir -p "$basedir"
  ln -s "$SKS_BASE_DIR/membership" "$basedir/membership"
  < "$SKS_BASE_DIR/sksconf" > "$basedir/sksconf" perl -pi -e "
    next if /^nodename/;
    next if /^recon_address/;
    next if /^recon_port/;
    next if /^hkp_address/;
    next if /^hkp_port/;
    next if /^gossip_interval/;
    next if /^stat_hour/;
    next if /^use_port_80/;
  "
  cat <<EOF >> "$basedir/sksconf"

# Added by script
nodename: $nodename
recon_address: 127.0.0.1
recon_port: $recon_port
hkp_address: 127.0.0.1
hkp_port: $khp_port
gossip_interval: ${CICADA_INTERVALS[$i]}
stat_hour: $i
EOF

  # add self to (shared) membership
  echo "127.0.0.1 $recon_port # $nodename" >> "$SKS_BASE_DIR/membership"

  # clone services
  < "$SYSTEMD_UNIT_DIR/sks-recon.service" > "$SYSTEMD_CONF_DIR/sks-recon-$i.service" perl -pi -e "
    s,sks\.service,sks-$i.service,;
    s,$SKS_DATA_DIR,$SKS_DATA_DIR.$i,;
    s,(RuntimeDirectory=.*),\1.$i,;
    s,(User=.*),User=$daemon_user,;
    s,(ExecStart=/usr/sbin/sks),\1 -basedir $basedir,;
  "
  < "$SYSTEMD_UNIT_DIR/sks.service" > "$SYSTEMD_CONF_DIR/sks-$i.service" perl -pi -e "
    s,sks-recon\.service,sks-recon-$i.service,;
    s,$SKS_DATA_DIR,$SKS_DATA_DIR.$i,;
    s,(RuntimeDirectory=.*),\1.$i,;
    s,(User=.*),User=$daemon_user,;
    s,(ExecStart=/usr/sbin/sks),\1 -basedir $basedir,;
  "
  
  systemctl enable sks-$i
  systemctl start sks-$i
done

# start main service
systemctl start sks

echo "Now reconfigure your webserver"
